version: "3.5"

services:
  backend:
    image: your-backend-image:1.0.0
    container_name: smoothstack-backend
    ports:
      - "9002:9002"
    environment:
      NODE_ENV: production
      DATABASE_URL: mongodb://mongo:27017/daraja_db
      API_KEY: ${BACKEND_API_KEY}
      PORT: 9001
    networks:
      - daraja
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  daraja:
    name: daraja-network
    external: true
