server:
  port: 9002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_manager_schema?useSSL=false&allowPublicKeyRetrieval=true
    username: collo
    password: Kipkirui92?
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    active: test
  task:
    scheduling:
      pool:
        size: 2

logging:
  level:
    org:
      hibernate: DEBUG
      hibernate.SQL: DEBUG

app:
  base-url: http://localhost:9002
  email:
    retry:
      max-attempts: 3
      delay-hours: 1
  jwt:
    secret: CvsHphcFevtdY3HnphT7gUvnIgDin5hlQG+9O1cCD7vhGEltf+QsEasz1n91kqFCf8vkB4RDnf5nAfblMR+CgA==
    token-validity: 3600000
    refresh-token-validity: 2592000000
